apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    name: nginx-dns  
  name: nginx-dns
spec:  
  replicas: 2
  selector:  
    matchLabels: 
      app: nginx-dns 
  template:  
    metadata: 
      labels:  
        app: nginx-dns 
    spec:  
      containers:  
      - image: nginx 
        name: nginx
        ports: 
        - containerPort: 80
          protocol: TCP
          name: http 
      - image: busybox:1.28
        name: busybox
        command: 
        - sleep
        - "3600"  

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-busybox
  name: nginx-busbox
spec:
  selector:
    app: nginx-dns
  ports:
  - name: service-port
    port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
