apiVersion: extensions/v1beta1
kind: ReplicaSet 
metadata: 
  labels: 
    name: kuard-rs 
  name: kuard-rs 
spec:  
  replicas: 3 
  selector:  
    matchLabels: 
      app: kuard-rs-pod 
  template:  
    metadata: 
      labels:  
        app: kuard-rs-pod 
    spec:  
      containers:  
      - image: gcr.io/kuar-demo/kuard-amd64:1 
        name: kuard
        ports: 
        - containerPort: 80
          protocol: TCP
          name: http 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kuards-rs-test-service
  name: kuards-rs-test-service
spec:
  selector:
    app: kuard-rs-pod
  ports:
  - name: service-port
    port: 81
    targetPort: 80
    protocol: TCP
  type: NodePort
