apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
  - name: memcached
    image: memcashed
    ports:
    - containerPort: 11211
  - name: consul
    image: consul
    ports:
    - containerPort: 8301
