apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-test
spec:  
  replicas: 3 
  selector:  
    app: nginx-rc-test
  template:  
    metadata: 
      labels:  
        app: nginx-rc-test 
    spec:  
      containers:  
      - name: nginx 
        image: nginx
        ports: 
        - containerPort: 80
          protocol: TCP
          name: http 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-rs-test-service
  name: nginx-rs-test-service
spec:
  selector:
    app: nginx-rc-test
  ports:
  - name: service-port
    port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
