apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql     
  name: secret-deployment-mysql
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mysql  
  template:
    metadata:
      labels:
        app: mysql       
    spec:
      containers:
      - name: mysql 
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials 
              key: password
        ports: 
        - containerPort: 3306
          
             
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
