apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: vlm
      mountPath: /app-creds
  volumes:
  - name: vlm
    secret:
      secretName: secret-creds
