apiVersion: extensions/v1beta1
kind: ReplicaSet 
metadata: 
  labels: 
    app: mysql
  name: mysql 
spec:  
  replicas: 1 
  selector:  
    matchLabels: 
      app: mysql 
  template:  
    metadata: 
      labels:  
        app: mysql
    spec:  
      containers:  
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mysql-credentials  
              key: password 
        ports:  
        - containerPort: 3306 
        
