apiVersion: v1 
kind: Pod 
metadata: 
  name: fortune-pod 
spec: 
  containers: 
  - name: nginx 
    image: nginx:1.14.0 
    volumeMounts:
    - name: data 
      mountPath: /usr/share/nginx/html  
  volumes: 
  - name: data 
    emptyDir: {}
